### PR TITLE
Fix a crash when an OMEMO message is carboned from Conversations

### PR DESCRIPTION
**Pull request by XRevan86**

### CODE REVIEW

**Comment by gkdr** [comment]
Thanks, shot myself in the foot there. I should stop setting the stanza to `null` in _lurch_.
I might do some changes so that it fits more with my codestyle, though.

**Comment by XRevan86** [comment]
> I might do some changes so that it fits more with my codestyle, though.

If you mean ```g_strcmp0 () != 0```, then it is recommended to have an explicit "0" there, because it is not a logical expression. After all, 0 (FALSE) is _success_ for strcmp.
[GTK+ C Coding Style](https://developer.gnome.org/programming-guidelines/stable/c-coding-style.html.en) agrees ;-).

**Comment by EionRobb** [comment]
or use `purple_strequal()` (which is just a wrapper for `g_strcmp0()`) as it's slightly clearer about what's going on?

**Comment by XRevan86** [comment]
```c
gboolean
purple_strequal(const gchar *left, const gchar *right)
{
	return (g_strcmp0(left, right) == 0);
}
```
Interesting choice, Pidgin :-).

**Comment by EionRobb** [comment]
It used to be a lot more of a complicated function, before `g_strcmp0()` existed :)

**Comment by XRevan86** [comment]
@EionRobb, ah, now it makes more historical sense :-).

**Pull request merged**
